INSERT INTO DERSLIK(DERSLIK_ID,DERSLIK_AD,DERSLIK_KAPASITE) VALUES(1,'A101',100);
INSERT INTO DERSLIK(DERSLIK_ID,DERSLIK_AD,DERSLIK_KAPASITE) VALUES(2,'A102',200);
INSERT INTO DERSLIK(DERSLIK_ID,DERSLIK_AD,DERSLIK_KAPASITE) VALUES(3,'A103',100);
INSERT INTO DERSLIK(DERSLIK_ID,DERSLIK_AD,DERSLIK_KAPASITE) VALUES(4,'B101',100);
INSERT INTO DERSLIK(DERSLIK_ID,DERSLIK_AD,DERSLIK_KAPASITE) VALUES(5,'B102',150);
INSERT INTO DERSLIK(DERSLIK_ID,DERSLIK_AD,DERSLIK_KAPASITE) VALUES(6,'B103',60);
