INSERT INTO DERS(DERS_ID,DERS_AD) VALUES(1,'Veri Tabaný Yönetimi');
INSERT INTO DERS(DERS_ID,DERS_AD) VALUES(2,'Görsel Programlama');
INSERT INTO DERS(DERS_ID,DERS_AD) VALUES(3,'Muhasebe');
INSERT INTO DERS(DERS_ID,DERS_AD) VALUES(4,'Ýþletme');
INSERT INTO DERS(DERS_ID,DERS_AD) VALUES(5,'Ýnternet Programlama');
